version: '3'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.9.2
    container_name: doctor_who_elasticsearch
    environment:
      - bootstrap.memory_lock=true
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9200:9200
  kibana:
    image: docker.elastic.co/kibana/kibana:7.9.2
    container_name: doctor_who_kibana
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
    ports:
        - 5601:5601
    depends_on:
        - elasticsearch
